analytics_dashboard/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from .views import home_view, login_view, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('performance/', include('products.urls', namespace = 'products')),
    path('upload/', include('csvs.urls', namespace = 'csvs')),
    path('customers/', include('customers.urls', namespace = 'customers')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

#if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

csvs/urls.py
from django.urls import path
from .views import upload_file_view

app_name = 'csvs'

urlpatterns = [
    path('', upload_file_view, name='upload-view'),
]

customers/urls.py
from django.urls import path
from .views import customer_corr_view

app_name = 'customers'

urlpatterns = [
    path('', customer_corr_view, name='main-customers-view'),
]

products/urls.py
from django.urls import path
from .views import chart_select_view, add_purchase_view, sales_dist_view

app_name = 'products'

urlpatterns = [
    path('', chart_select_view, name='main-product-view'),
    path('add/', add_purchase_view, name='add-purchase-view'),
    path('sales/', sales_dist_view, name='sales-view'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <!--JQuery-->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <!--Custom css-->
    <link rel="stylesheet" type="text/css" href={% static "style.css" %}>
    <!--semantic ui-->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>

    <title>Analytics Dashboard - {% block title %}{% endblock title %}</title>
</head>
<body>

    {% include "navbar.html" %}

    <div class="ui container">
        {% block content %}

        {% endblock content %}
    </div>
    
    <script type="text/javascript" src={% static 'main.js' %}></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Home {% endblock title %}

{% block content %}

    <div class="block-center">
        <img src={% static 'main.jpg' %} alt="home page picture" class="ui centered fluid huge image">
    </div>

{% endblock content %}

templates/login.html
{% extends 'base.html' %}

{% block title %} Login {% endblock title %}

{% block content %}

    <div class="block-center">
        {% if error_message %}
            <div class="ui negative message">
                <i class="close icon"></i>
                <div class="header">
                    {{ error_message }}
                </div>
            </div>
        {% endif %}
        <div class="ui middle aligned center aligned grid" style="margin-top: 4em;">
            <form action="" method="POST" class = "ui form">
                {% csrf_token %}
                {{ form }}
                <button type="submit" class="ui button positive mtop">Login</button>
            </form>
        </div>
    </div>

{% endblock content %}

templates/navbar.html
{% url 'home' as path_to_home %}
{% url 'login' as path_to_login %}
{% url 'logout' as path_to_logout %}
{% url 'products:main-product-view' as path_to_performance %}
{% url 'products:add-purchase-view' as path_to_adding_records %}
{% url 'csvs:upload-view' as path_to_upload %}
{% url 'customers:main-customers-view' as path_to_customers %}
{% url 'products:sales-view' as path_to_sales %}


      <div class="ui huge stackable menu"> <!--secondary pointing menucomputer only row -->
        <a href={{ path_to_home }} class="{% if request.path == path_to_home %}active{% endif %} item">
          <i class="home icon"></i><strong>Home</strong>
        </a>
        {% if request.user.is_authenticated %}
          <a href={{ path_to_performance }} class="{% if request.path == path_to_performance %}active{% endif %} item">
            <i class="bi bi-graph-up-arrow"></i><strong>Performance</strong>
          </a>
          <a href={{ path_to_sales }} class="{% if request.path == path_to_sales %}active{% endif %} item">
            <i class="dollar sign icon"></i><strong>Sales</strong>
          </a>
          <a href={{ path_to_customers }} class="{% if request.path == path_to_customers %}active{% endif %} item">
            <i class="user icon"></i><strong>Customers</strong>
          </a>
          <a href={{ path_to_adding_records }} class="{% if request.path == path_to_adding_records %}active{% endif %} item">
            <i class="database icon"></i><strong>Add Records</strong>
          </a>
          <a href={{ path_to_upload }} class="{% if request.path == path_to_upload %}active{% endif %} item">
            <i class="upload icon"></i><strong>Upload File</strong>
          </a>
          <div class="right menu">
            <a href={{ path_to_logout }} class="ui item {% if request.path == path_to_login %}active{% endif %}">
              <i class="sign out alternate icon"></i><strong>Logout</strong>
            </a>
          </div>
        {% else %}
          <div class="right menu">
            <a href={{ path_to_login }} class="ui item {% if request.path == path_to_login %}active{% endif %}">
              <i class="sign in alternate icon"></i><strong>Login</strong>
            </a>
          </div>
        {% endif %}
      </div>